# Generated by Django 4.2.2 on 2023-06-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(default='Software Developer', max_length=40)),
                ('company_name', models.CharField(max_length=40)),
                ('description_link', models.URLField()),
                ('notes', models.TextField(null=True)),
            ],
        ),
    ]
